add_newline = true

[character]
success_symbol = "🚀 "

[git_status]
conflicted = "🏳 "
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = "➕"
renamed = "👅"
deleted = "🗑"
show_sync_count = true
